server {
    listen 80;
    
    # Kořenový adresář, kde budou naše zkompilované soubory
    root /usr/share/nginx/html;
    index index.html;

    # Hlavní pravidlo pro React Router
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Volitelně: Cache pro statické soubory (obrázky, styly), aby se načítaly rychleji
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
        expires 1y;
        add_header Cache-Control "public, no-transform";
    }
}